### PR TITLE
🍔  new content menu part deux

### LINKED ISSUE #217: Add ContentMenu Component
Create a new component to render the in-page dropdown menus. 

JSON endpoints already exist by sending the header `Temba-Content-Menu: 1`

See here:
https://github.com/nyaruka/rapidpro/blob/79671dec985e0a145d3771e32deaea02e0f850d5/temba/utils/views.py#L408

### PR DESCRIPTION
**Pull request by susanm74**
- legacy (version) property working
- query (search) property working

closes #217 

the rapidpro PR can be found here https://github.com/nyaruka/rapidpro/pull/4192

### CODE REVIEW

**Comment by susanm74** [comment]
@ericnewcomer this is RFR

**Comment by susanm74** [comment]
@ericnewcomer hmm, so i'm currently getting one failed test on the server (temba-contact-history > expands event groups), but all of the tests are passing for me locally - what's odd is that nothing about the contact history changed, so i'm gonna just try re-running the failed jobs and see if that resolves it

**Comment by susanm74** [comment]
@ericnewcomer sweet, looks like everything's passing now 😎

**Comment by ericnewcomer** [comment]
Waiting to look at this one until the build is passing on https://github.com/nyaruka/rapidpro/pull/4192

**Pull request merged**
