### PR TITLE
Abstract attachments into new components

### LINKED ISSUE #329: Abstract attachments out of compose its own components

### PR DESCRIPTION
**Pull request by susanm74**
fixes #329

### CODE REVIEW

**Comment by ericnewcomer** [comment]
Didn't get to this today due to form element drama this morning. Will look at it tomorrow though!

**Comment by susanm74** [comment]
@ericnewcomer i'm still getting sorted with my local environment, so i still haven't done some final e2e testing on the compose updates, so although this is ready to review, i'm leaving it marked as draft as it's still not quite ready to merge until i've done that

**Comment by ericnewcomer** [comment]
Are you still around that we can look at that today?

**Comment by ericnewcomer** [comment]
Had a look through this, I do have some comments, but I'd like to see it in an application before discussing it further.

**Pull request closed without merging**
